Roms:
    Ignore hashes: false # If true, Pilgrim will skip verifying that vanilla ROMs are in fact vanilla. While some features may work, Pilgrim is not tested or designed to work using modified ROMs as "vanilla". Here be dragons! 
    Vanilla EU: 'vanilla-eu.nds' # Path to vanilla EU ROM, relative to project root
    Vanilla NA: 'vanilla-na.nds' # Path to vanilla NA ROM, relative to project root
    Mod EU: 'mod-eu.nds' # Path to modified EU ROM, relative to project root    
    Mod NA: 'mod-na.nds' # Path to modified NA ROM, relative to project root. This file does not need to be provided, as it is the output!
OffsetMaps:
    #'22e7b88': '22e7248' # ProcStartAddress
    #'2003d70': '2003d70' # CardPullOut
    #'22e7bcc': '22e850c'
    #'204b824': '204b4ec' # LoadScriptVariableValue
    #'204bcc0': '204b988' # SaveScriptVariableValueAtIndex
    #'22e8400': '22e7ac0' # ProcJumpAddress
    #'023de0ac': '23de0ac' # teeeechnically redundant but i'm putting it here just to make it easier to visualize consistency. this is an ov36 address
    #'204b9b0': '204b678' # LoadScriptVariableValueAtIndex
    #'22e7bb8': '22e7278'
    #'22e7ba0': '22e7260'
    #'22e7c0c': '22e72cc'
    #'22e7be8': '22e72a8'
    #'22e7bf8': '22e72b8'
    #'204bb58': '204b820' # SaveScriptVariableValue
    #'2065fc4': '2065c48' # RandomizeDemoActors
Patches:
  ExtraSpace:
  AddKeyCheck:
  AppraiseAll:
    MenuOptionStringID: 300
    AppraiseAllConfirmStringID: 301
    AppraiseRevealBeforeStringID: 302
    AppraiseRevealItemStringID: 303
    ReplaceStrings: '1'
    BoxCost: 150
  NoWeatherStop:
  AntiSoftlock:
  DisplayScriptVariable:
  MoveShortcuts:
  EditGuestPokemon:
  ExternalizeMappaFile:
  ExtractHardcodedItemLists:
  ExtractSPCode:
